# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:

  # Shrug..
  - trigger: ":shrug"
    replace: '¯\_(ツ)_/¯'

  # Euro Symbol - why you no exist on my keyboard?!
  - trigger: ":euro"
    replace: "€"

  # Mishacreatrix
  - trigger: ":mx"
    replace: "https://mishacreatrix.com/"

  # Mishacreatrix Pink Hex Value
  - trigger: ":mpink"
    replace: "#DB1F5F"

  # Twitter
  - trigger: ":twitter"
    replace: "https://twitter.com/MishaCreatrix"

  # Bullet point (for Tweets)
  - trigger: ":bull"
    replace: '•'

  # Date
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y%m%d"

  # Time
  - trigger: ":time"
    replace: "{{mytime}}"
    vars:
      - name: mytime
        type: date
        params:
          format: "%H:%M"

