# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso:date

matches:
  # Symbols
  - trigger: "->"
    replace: " ➜"
  - trigger: ":euro"
    replace: "€"
  - trigger: ":bull"
    replace: "•"
  - trigger: ":gc"
    replace: "🟢"
  - trigger: ":pipe"
    replace: "|"
  - trigger: ":oc"
    replace: "🟠"
  - trigger: ":wc"
    replace: "⚪"
  - trigger: ":cluster"
    replace: "❇️"

  # Code Snippets
  - trigger: ":ext"
    replace: '{:target="_blank"}{:rel="noopener noreferrer"}'
  - trigger: ":sc"
    replace: "?utm_source=DesignInsightNewsletter"

  # Links
  - trigger: ":twit"
    replace: "https://twitter.com/heymichellemac"
  - trigger: ":mx"
    replace: "https://heymichellemac.com/"
  - trigger: ":mas"
    replace: "https://pkm.social/@heymichellemac"

  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y%m%d"

  - trigger: ":time"
    replace: "{{mytime}}"
    vars:
      - name: mytime
        type: date
        params:
          format: "%H:%M"

  # Dates
  - trigger: ":ldate"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Shell commands
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"
